# Generated by Django 3.0.5 on 2020-04-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20200405_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
